apiVersion: v1
kind: Service
metadata:
  name: thirdeye-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: thirdeye-backend
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app: thirdeye-backend
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 8000
      protocol: TCP
