apiVersion: apps/v1
kind: Deployment
metadata:
  name: thirdeye-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: thirdeye-frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: thirdeye-frontend
  template:
    metadata:
      labels:
        app: thirdeye-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.registry }}/{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: {{ .Values.resources.frontend.requests.cpu }}
              memory: {{ .Values.resources.frontend.requests.memory }}
            limits:
              cpu: {{ .Values.resources.frontend.limits.cpu }}
              memory: {{ .Values.resources.frontend.limits.memory }}
